fixtures:
  symlinks:
    unifi: "#{source_dir}"
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref:  '4.6.0'
    apt:
      repo: 'https://github.com/puppetlabs/puppetlabs-apt.git'
      ref:  '2.3.0'
    java_ks:
      repo: 'https://github.com/puppetlabs/puppetlabs-java_ks.git'
      ref:  '1.4.1'
