---
language: ruby
bundler_args: --without development
script: bundle exec rake test
cache:
  bundler: true
matrix:
  include:
    - rvm: '1.9.3'
      env: PUPPET_VERSION="~> 3.0"
    - rvm: '2.0.0'
      env: PUPPET_VERSION="~> 3.0"
    - rvm: '2.1.5'
      env: PUPPET_VERSION="~> 4.0"
